exports.blackCards = [`And the BAFTA for ______ goes to ______.`,
    `And what did you bring for show and tell?`,
    `Anthropologists have recently discovered a primitive tribe that worships ______.`,
    `Arby's: We Have ______.`,
    `Are you thinking what I'm thinking, B1?
    
    I think I am, B2: it's ______ time!`,
    `As my New Year's resolution, I vow to give up ______.`,
    `As the mom of five rambunctious boys, I'm no stranger to ______.`,
    `As the mum of five rambunctious boys, I'm no stranger to ______.`,
    `Betcha can't have just one!`,
    `BILLY MAYS HERE FOR ______.`,
    `Bravo's new reality show features eight washed-up celebrities living with ______.`,
    `Brought to you by Bud Light®, the Official Beer of ______.`,
    `Brought to you by Molson Canadian, the Official Beer of ______.`,
    `Brought to you by XXXX Gold, the Official Beer of ______.`,
    `But before I kill you, Mr. Bond, I must show you ______.`,
    `CBC presents "___: the Story of ___."`,
    `Channel 4 presents ______, the story of ______.`,
    `Channel 4 presents "______: the Story of ______."`,
    `Channel 5's new reality show features eight washed-up celebrities living with ______.`,
    `Channel 9 is pleased to present its new variety show, "Hey Hey It's ______."`,
    `Charades was ruined for me forever when my mom had to act out ______.`,
    `Check me out, yo! I call this dance move "______."`,
    `Click Here for ______!!!`,
    `Coming this season, Samuel Beckett's classic existential play: Waiting for ______.`,
    `Coming to Broadway this season, ______: The Musical.`,
    `Coming to the West End this year, ______: The Musical.`,
    `Crikey! I've never seen ______ like this before! Let's get a bit closer.`,
    `CTV presents "______: the Story of ______."`,
    `Daddy, why is mommy crying?`,
    `Daddy, why is mummy crying?`,
    `Dear Abby, I'm having some trouble with ______ and would like your advice.`,
    `Dear Agony Aunt, I'm having some trouble with ________ and I need your advice.`,
    `Dear Agony Aunt, I'm having some trouble with ________ and would like your advice.`,
    `Dear Sir or Madam, We regret to inform you that the Office of ______ has denied your request for ______.`,
    `Doctor, you've gone too far! The human body wasn't meant to withstand that amount of ______!`,
    `Dude, do not go in that bathroom. There's ______ in there.`,
    `Dude, do not go in that washroom. There's ______ in there.`,
    `Due to a PR fiasco, Walmart no longer offers ______.`,
    `During his childhood, Salvador Dali produced hundreds of paintings of ______.`,
    `During his midlife crisis, my dad got really into ______.`,
    `During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of ______.`,
    `During sex, I like to think about ______.`,
    `Finally! A service that delivers ______ right to your door.`,
    `For my next trick, I will pull ______ out of ______.`,
    `Fun tip! When your man asks you to go down on him, try surprising him with ______ instead.`,
    `Future historians will agree that ______ marked the beginning of America's decline.`,
    `Having problems with ______? Try ______!`,
    `"Here is the church
    Here is the steeple
    Open the doors
    And there is ______."`,
    `Hey guys, welcome to Boston Pizza! Would you like to start the night off right with ______?`,
    `Hey guys, welcome to Chili's! Would you like to start the night off right with ______?`,
    `Hey guys, welcome to Sizzler! Would you like to start the night off right with ______?`,
    `Hey guys, welcome to TGI Fridays! Would you like to start the night off right with ______?`,
    `Hey guys, welcome to TGIF! Would you like to start the night off right with ______?`,
    `Hey Reddit! I'm ______. Ask me anything.`,
    `How am I maintaining my relationship status?`,
    `How did I lose my virginity?`,
    `I do not know with what weapons World War III will be fought, but World War IV will be fought with ______.`,
    `I drink to forget ______.`,
    `I get by with a little help from ______.`,
    `I got 99 problems but ______ ain't one.`,
    `I know when that hotline bling, that can only mean one thing: ______.`,
    `I'm Lebron James, and when I'm not slamming dunks, I love ______.`,
    `I'm no doctor, but I'm pretty sure what you're suffering from is called "______."`,
    `I'm sorry, Professor, but I couldn't complete my homework because of ______.`,
    `I'm sorry, Sir, but I couldn't complete my homework because of ______.`,
    `I’m not like the rest of you. I’m too rich and busy for ______.`,
    `If you can't be with the one you love, love ______.`,
    `IF you like ______, YOU MIGHT BE A REDNECK.`,
    `In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?`,
    `In 1,000 years, when paper money is but a distant memory, ______ will be our currency.`,
    `In a world ravaged by ______ our only solace is ______.`,
    `In a world ravaged by ______, our only solace is ______.`,
    `In an attempt to reach a wider audience, the National Museum of Australia has opened an interactive exhibit on ______.`,
    `In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on ______.`,
    `In Australia, ______ is twice as big and twice as deadly.`,
    `In Belmarsh Prison, word is you can trade 200 cigarettes for ______.`,
    `In her latest feature-length film, Tracy Beaker struggles with ______ for the first time.`,
    `In his new self-produced album, Kanye West raps over the sounds of ______.`,
    `In his new summer comedy, Rob Schneider is ______ trapped in the body of ______.`,
    `In L.A. County Jail, word is you can trade 200 cigarettes for ______.`]


