// AKA PROMPT CARDS

exports.whiteCards = [
`A bag of magic beans.`,
`A ball of earwax, semen, and toenail clippings.`,
`A big hoopla about nothing.`,
`A bit of slap and tickle.`,
`A bleached arsehole.`,
`A Bop It™.`,
`A brain tumor.`,
`A bucket of fish heads.`,
`A caress of the inner thigh.`,
`A cat video so cute that your eyes roll back and your spine slides out of your anus.`,
`A Chinese tourist who wants something very badly but cannot communicate it.`,
`A comprehensive understanding of the Irish backstop.`,
`A cop who is also a dog.`,
`A cute, fuzzy koala, but it has chlamydia.`,
`A decent fucking Internet connection.`,
`A defective condom.`,
`A didgeridildo.`,
`A drive-by shooting.`,
`A falcon with a cap on its head.`,
`A fart so powerful that it wakes the giants from their thousand-year slumber.`,
`A fetus.`,
`A Fleshlight.`,
`A foetus.`,
`A fuck-ton of almonds.`,
`A gassy antelope.`,
`A gentle caress of the inner thigh.`,
`A Ginsters pasty and three cans of Monsters Energy.`,
`A good, strong gorilla.`,
`A grande sugar-free iced soy caramel macchiato.`,
`A hairless little shitstain named Callou.`,
`A hen night in Slough.`,
`A horde of Vikings.`,
`A Japanese toaster you can fuck.`,
`A LAN party.`,
`A literal tornado of fire.`,
`A live studio audience.`,
`A low standard of living.`,
`A madman who lives in a police box and kidnaps women.`,
`A man on the brink of orgasm.`,
`A meat raffle!`,
`A micropenis.`,
`A middle-aged man on roller skates.`,
`A moment of silence.`,
`A mopey zoo lion.`,
`A murder most foul.`,
`A nice cup of tea.`,
`A piñata full of scorpions.`,
`A PowerPoint presentation.`,
`A really cool hat.`,
`A sad fat dragon with no friends.`,
`A salad for men that's made of metal.`,
`A sassy black woman.`,
`A saxophone solo.`,
`A shark!`,
`A sick wombat.`,
`A six-point plan to stop the boats.`,
`A slightly salty toad in the hole.`,
`A snapping turtle biting the tip of your penis.`,
`A soggy Sao.`,
`A stingray barb through the chest.`,
`A subscription to Men's Fitness.`,
`A surprising amount of hair.`,
`A thermonuclear detonation.`,
`A three-way with my wife and Shaquille O'Neal.`,
`A time travel paradox.`,
`A tiny, gay guitar called a ukulele.`,
`A vagina that leads to another dimension.`,
`A vastly superior healthcare system.`,
`A web of lies.`,
`A white ethnostate.`,
`A whole thing of butter.`,
`A wisecracking terrorist.`,
`Aaron Burr.`,
`Academy Award winner Meryl Streep.`,
`Accidentally slipping yourself a roofie.`,
`Actually getting shot, for real.`,
`Adderall™.`,
`Advice from a wise, old black man.`,
`Agriculture.`,
`Ainsley Harriott.`,
`Alcoholism.`,
`All four prongs of an echidna's penis.`,
`All my gentleman suitors.`,
`All the dudes I've fucked.`,
`All-you-can-eat shrimp for $8.99.`,
`America.`,
`Americanization.`,
`An AK-47 assault rifle.`,
`An AR-15 assault rifle.`,
`An army of skeletons.`,
`An asymmetric boob job.`,
`An endless stream of diarrhoea.`,
`An erection that lasts longer than four hours.`,
`An evil man in evil clothes.`,
`An icepick lobotomy.`,
`An M. Night Shyamalan plot twist.`,
`An octopus giving seven handjobs and smoking a cigarette.`,
`An old guy who's almost dead.`,
`An oversized lollipop.`,
`An unstoppable wave of fire ants.`,
`An uppercut.`,
`Announcing that I am about to cum.`,
`Another shot of morphine.`,
`Apologizing.`,
`Asians who aren't good at math.`,
`Attitude.`,
`Australia.`,
`Autocannibalism.`,
`Badger culling.`,
`Balls.`,
`Bananas.`,
`Barely making $25,000 a year.`,
`Basic human decency.`,
`BATMAN!!!`,
`Becoming a blueberry.`,
`Being a busy adult with many important things to do.`,
`Being a dinosaur.`,
`Being a motherfucking sorcerer.`,
`Being a woman.`,
`Being awesome at sex.`,
`Being Canadian.`,
`Being fat and stupid.`,
`Being hunted like a fox.`,
`Being marginalized.`,
`Being rich.`,
`Benedict Cumberbatch.`,
`Bill Nye the Science Guy.`,
`Bio-engineered assault turtles with acid breath.`,
`Bitches.`,
`Bling.`,
`Blood, sweat, and tears.`,
`Blowing my boyfriend so hard he shits.`,
`Boat people; half boat, half human.`,
`Bond, James Bond.`,
`Booby-trapping the house to foil burglars.`,
`Boris Johnson.`,
`Braiding three penises into a Curly Wurly.`,
`Braiding three penises into a Twizzler.`,
`Brexit.`,
`Brown people.`,
`Bubble butt bottom boys.`,
`Bullshit.`,
`Buying the right pants to be cool.`,
`Canadian Netflix.`,
`Capturing Newt Gingrich and forcing him to dance in a monkey suit.`,
`Cards Against Humanity.`,
`Casually suggesting a threesome.`,
`Centaurs.`,
`Charisma.`,
`Cheating in the Special Olympics.`,
`Chemical weapons.`,
`Child beauty pageants.`,
`Chivalry.`,
`Chundering into a kangaroo's pouch.`,
`Chunks of dead hitchhiker.`,
`Chutzpah.`,
`Classist undertones.`,
`Clubbing baby seals.`,
`Cock.`,
`College.`,
`Completely unwarranted confidence.`,
`Concealing an erection.`,
`Consultants.`,
`Converting to Islam.`,
`Copping a feel.`,
`Count Chocula.`,
`Covering myself with Parmesan cheese and chili flakes because I am pizza.`,
`Creed.`,
`Crucifixion.`,
`Crumbs all over the god damn carpet.`,
`Crystal meth.`,
`Cumming deep inside my best bro.`,
`Customer service representatives.`,
`Deflowering the princess.`,
`Denying climate change.`,
`Dick Cheney.`,
`Dick pics.`,
`Dirty nappies.`,
`Discovering he's a Tory.`,
`Dogging.`,
`Doin' it up the bum.`,
`Doing crimes.`,
`Doing the right thing.`,
`Don Cherry's wardrobe.`,
`Donald Trump.`,
`Douchebags on their iPhones.`,
`Drinking alone.`,
`Drinking out of the toilet and eating rubbish.`,
`Dropping a chandelier on your enemies and riding the rope up.`,
`Druids.`,
`Dry heaving.`,
`Dwayne "The Rock" Johnson.`,
`Dying of dysentery.`,
`Eastern European Turbo-Folk music.`,
`Eating a hard boiled egg out of my husband's asshole.`,
`Eating an albino.`,
`Eating too much of a lamp.`,
`Ed Balls.`,
`Edible underwear.`,
`Elderly Japanese men.`,
`Embryonic stem cells.`,
`Emma Watson.`,
`England.`,
`Establishing dominance.`,
`Fading away into nothingness.`,
`Faith healing.`,
`FALCON PUNCH!!!`,
`Fancy Feast®.`,
`Farting into your petticoats and wafting it at Lord Gregory.`,
`Feeding Rosie O'Donnell.`,
`Fiery poops.`,
`Figgy pudding.`,
`Filling my son with spaghetti.`,
`Finger painting.`,
`Firing a rifle into the air while balls deep in a squealing hog.`,
`Five litres of Special Brew.`,
`Flash flooding.`,
`Flavored condoms.`,
`Flightless birds.`,
`Flying sex snakes.`,
`Forced sterilization.`,
`Forgetting the Alamo.`,
`Four Loko.`,
`Fragile masculinity.`,
`Friction.`,
`Friends who eat all the snacks.`,
`Friends with benefits.`,
`Front butt.`,
`Fucking the weatherman on live television.`,
`Funky fresh rhymes.`,
`Gandhi.`,
`Gary Coleman.`,
`Gay aliens.`,
`Geese.`,
`Genghis Khan.`,
`Gentleman's Relish®.`,
`German Chancellor Angela Merkel.`,
`Germans on holiday.`,
`Ghosts.`,
`Girls.`,
`Giving birth to the Antichrist.`,
`Glassing a wanker.`,
`Glenn Beck catching his scrotum on a curtain hook.`,
`Glenn Beck.`,
`Gloryholes.`,
`Goblins.`,
`GoGurt®.`,
`Going around punching people.`,
`Good-natured, fun-loving Aussie racism.`,
`Grandpa's ashes.`,
`Grave robbing.`,
`Guys who don't call.`,
`Half a kilo of pure China White heroin.`,
`Harry Potter erotica.`,
`Having a Golden Gaytime.`,
`Heath Ledger.`,
`Her Majesty, Queen Elizabeth II.`,
`Heritage minutes.`,
`Heroin.`,
`Hillary Clinton's emails.`,
`Hipsters.`,
`Hobos.`,
`Home video of Oprah sobbing into a Lean Cuisine®.`,
`Hope.`,
`Horrifying laser hair removal accidents.`,
`Hospice care.`,
`Hunting "accidents".`,
`Hurling one's body down a hill in pursuit of a wheel of cheese.`,
`Hurting those closest to me.`,
`Ice.`,
`Impotence.`,
`Indescribable loneliness.`,
`Inserting a Mason jar into my anus.`,
`Intimacy problems.`,
`Irritable Bowel Syndrome.`,
`Jade Goody's cancerous remains.`,
`Jedward.`,
`Jennifer Lawrence.`,
`Jesus.`,
`Jewish fraternities.`,
`Jibber-jabber.`,
`Jobs.`,
`John Howard's eyebrows.`,
`Judge Judy.`,
`Just touching David Beckham's hair.`,
`Justin Trudeau.`,
`Kamikaze pilots.`,
`Keanu Reeves.`,
`Keg stands.`,
`Kibbles n' Bits.`,
`Kids with bum cancer.`,
`Kim Jong-un.`,
`Kissing nan on the forehead and turning off her life support.`,
`Kourtney, Kim, Khloe, Kendall, and Kylie.`,
`Lads.`,
`Lance Armstrong's missing testicle.`,
`Laying an egg.`,
`Leaving an awkward voicemail.`,
`Leprosy.`,
`Looking in the mirror, applying lipstick, and whispering "tonight, you will have sex with Tom Cruise."`,
`Lumberjack fantasies.`,
`LYNX® Body Spray.`,
`Madeleine McCann.`,
`Making a friend.`,
`Making sex at her.`,
`Making up for centuries of oppression with one day of apologising.`,
`Mansplaining.`,
`Marky Mark and the Funky Bunch.`,
`Martin Lewis, Money Saving Expert.`,
`Masturbating.`,
`Mathletes.`,
`My sex life.`,
`My Uber driver, Ajay.`,
`My ugly face and bad personality.`,
`Nachos for the table.`,
`Natalie Portman.`,
`Natural selection.`,
`NBA superstar LeBron James.`,
`New Age music.`,
`Not wearing trousers.`,
`Nothing.`,
`Obesity.`,
`Oestrogen.`,
`Ominous background music.`,
`One Ring to rule them all.`,
`One trillion dollars.`,
`Oompa-Loompas.`,
`Oprah.`,
`Our first chimpanzee Prime Minister.`,
`Overpowering your father.`,
`Owning and operating a Chili's franchise.`,
`Pac-Man uncontrollably guzzling cum.`,
`Pooping back and forth. Forever.`,
`Pooping in the soup.`,
`Poor life choices.`,
`Public ridicule.`,
`Pumping out a baby every nine months.`,
`Punching an MP in the face.`,
`Pussy Galore.`,
`Queefing.`,
`Queuing.`,
`Racism.`,
`Rap music.`,
`Raptor attacks.`,
`Rectangles.`,
`Repression.`,
`Reverse cowgirl.`,
`Riding off into the sunset.`,
`Ring Pops™.`,
`Running out of semen.`,
`Rush Limbaugh's soft, shitty body.`,
`Ryan Gosling riding in on a white horse.`,
`Same-sex ice dancing.`,
`Santa Claus.`,
`Saxophone solos.`,
`Scalping the Milkybar Kid.`,
`Schmirler the Curler.`,
`Scientology.`,
`Scousers.`,
`Scrotum tickling.`,
`Sean Connery.`,
`Seduction.`,
`Seeing Granny naked.`,
`Seeing what happens when you lock people in a room with hungry seagulls.`,
`Self-flagellation.`,
`Selling crack to children.`,
`Seppuku.`,
`Seven dead and three in critical condition.`,
`Sex with Patrick Stewart.`,
`Sexual humiliation.`,
`Sexual tension.`,
`Shaking a baby until it stops crying.`,
`Shaquille O'Neal's acting career.`,
`Shiny objects.`,
`Shitting out a perfect Cumberland sausage.`,
`Shorties and blunts.`,
`Shutting the fuck up.`,
`Shutting up so I can watch the match.`,
`Silence.`,
`Sitting in a jar of vinegar all night because I am gherkin.`,
`Sitting on my face.`,
`Skeletor.`,
`Slapping a biscuit out of an orphan's mouth.`,
`Slapping Nigel Farage over and over.`,
`Slaughtering innocent civilians.`,
`Smallpox blankets.`,
`Sneezing, farting, and cumming at the same time.`,
`Sniffing glue.`,
`Sobbing into a Hungry-Man™ Frozen Dinner.`,
`Soiling oneself.`,
`Somali pirates.`,
`Some douche with an acoustic guitar.`,
`Some god damn peace and quiet.`,
`Some kind of bird man.`,
`Some punk kid who stole my turkey sandwich.`,
`Sorry, this content cannot be viewed in your region.`,
`Spaghetti? Again?`,
`Spectacular abs.`,
`Sperm whales.`,
`Spontaneous human combustion.`,
`Staring at a painting and going "hmmmmmmm..."`,
`Stephen Harper.`,
`Steve Bannon.`,
`Stifling a giggle at the mention of Hutus and Tutsis.`,
`Stockholm Syndrome.`,
`Stranger danger.`,
`Stunt doubles.`,
`Sucking some dicks to not get drafted.`,
`Suicidal thoughts.`,
`Sunshine and rainbows.`,
`Swag.`,
`Switching to Geico®.`,
`Synergistic management solutions.`,
`Take-backsies.`,
`Taking a sheep-wife.`,
`Tangled Slinkys.`,
`Tasteful sideboob.`,
`Team building exercises.`,
`Tearing that ass up like wrapping paper on Christmas morning.`,
`Telling a shitty story that goes nowhere.`,
`Terrorists.`,
`The deformed.`,
`The Donald Trump Seal of Approval.™`,
`The economy.`,
`The end of days.`,
`The entire Internet.`,
`The female orgasm.`,
`The flute.`,
`The forbidden fruit.`,
`The French.`,
`The glass ceiling.`,
`The Great Emu War.`,
`The guys from Queer Eye.`,
`The Hamburglar.`,
`The heart of a child.`,
`The hiccups.`,
`The Holy Bible.`,
`The human body.`,
`The illusion of choice in a late-stage capitalist society.`,
`The invisible hand.`,
`The KKK.`,
`The land of chocolate.`,
`The Little Engine That Could.`,
`The Make-A-Wish Foundation.`,
`The milk man.`,
`The miracle of childbirth.`,
`The North.`,
`The only gay person in a hundred kilometers.`,
`The opioid epidemic.`,
`The Scouts.`,
`The Smell of a Primark.`,
`The South.`,
`The Strictly Come Dancing final.`,
`The sudden appearance of the Go Compare man.`,
`The taint; the grundle; the fleshy fun-bridge.`,
`The terrorists.`,
`The Three-Fifths compromise.`,
`The token minority.`,
`The Trail of Tears.`,
`The Übermensch.`,
`The unstoppable tide of Islam.`,
`The Welsh.`,
`The wifi password.`,
`The World of Warcraft.`,
`Therapy.`,
`These hoes.`,
`This answer is postmodern.`,
`This year's mass shooting.`,
`Three dicks at the same time.`,
`Throwing grapes at a man until he loses touch with reality.`,
`Tickle Me Elmo™.`,
`Tiger Woods.`,
`Tom Cruise.`,
`Toni Morrison's vagina.`,
`Too much hair gel.`,
`Total control of the media.`,
`Trench foot.`,
`Tweeting.`,
`Twinkies®.`,
`Waterboarding.`,
`Wearing an octopus for a hat.`,
`Wearing underwear inside-out to avoid doing laundry.`,
`What that mouth do.`,
`When you fart and a little bit comes out.`,
`Whipping it out.`,
`Women of color.`,
`Women voting.`,
`Women's undies.`,
`Words.`,
`Worshipping that pussy.`,
`Yeast.`,
`Your mum.`,
`A narc.`,
`A supportive touch on the lower back.`,
`Black Jesus.`,
`Climbing a telephone pole and becoming one with the T-Mobile network.`,
`Crab.`,
`Grabbing my man by his love handles and fucking his big ass.`,
`My boss.`
]
